set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_SYSTEM_NAME MinGW)
set(VCPKG_TARGET_IS_MINGW ON)

set(VCPKG_ENV_PASSTHROUGH PATH)

if (DEFINED ENV{VCPKG_INSTALLATION_ROOT})
    set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE $ENV{VCPKG_INSTALLATION_ROOT}/mingw-cross-toolchain.cmake)
else ()
    set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/../../mingw-cross-toolchain.cmake)
endif ()

