set(OGG_FOUND TRUE)
set(OGG_INCLUDE_DIR "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
set(OGG_LIBRARY "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libogg.a")
set(OGG_INCLUDE_DIRS "${OGG_INCLUDE_DIR}")
set(OGG_LIBRARIES "${OGG_LIBRARY}")

if (NOT TARGET Ogg::Ogg)
    add_library(Ogg::Ogg STATIC IMPORTED GLOBAL)
    set_target_properties(Ogg::Ogg PROPERTIES
        IMPORTED_LOCATION "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libogg.a"
        INTERFACE_INCLUDE_DIRECTORIES "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include"
    )
endif ()

