set(BZIP2_FOUND TRUE)
set(BZIP2_INCLUDE_DIR "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
set(BZIP2_LIBRARIES "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libbz2.a")

set(BROTLIDEC_FOUND TRUE)
set(BROTLIDEC_INCLUDE_DIRS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
set(BROTLIDEC_LIBRARIES "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libbrotlidec.a;${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libbrotlicommon.a")
set(BROTLIDEC_INCLUDE_DIR "${BROTLIDEC_INCLUDE_DIRS}")
set(BROTLIDEC_LIBRARY "${BROTLIDEC_LIBRARIES}")
mark_as_advanced(BROTLIDEC_INCLUDE_DIR BROTLIDEC_LIBRARY)
mark_as_advanced(BROTLIDEC_INCLUDE_DIRS BROTLIDEC_LIBRARIES)

if(NOT TARGET BrotliDec)
    add_library(BrotliDec STATIC IMPORTED GLOBAL)
    set_target_properties(BrotliDec PROPERTIES
        IMPORTED_LOCATION "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libbrotlidec.a;${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libbrotlicommon.a"
        INTERFACE_INCLUDE_DIRECTORIES "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include"
    )
endif()

set(PNG_FOUND TRUE)
set(PNG_INCLUDE_DIR "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
set(PNG_PNG_INCLUDE_DIR "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
set(PNG_LIBRARY "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libpng16.a")

find_library(PNG_LIBRARY_RELEASE NAMES png16 libpng16 NAMES_PER_DIR PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib" NO_DEFAULT_PATH)
find_library(PNG_LIBRARY_DEBUG NAMES png16d libpng16d NAMES_PER_DIR PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug/lib" NO_DEFAULT_PATH)
_find_package(${ARGS})
